### ISSUE TITLE
ga tab completion

### ISSUE THREAD

**Issue by codenameEli** [ironcodestudio/ironcode-git-enhancements#3]
Example of issue:
<code>gs</code>
<code>modified: wp-content/themes/css/some-stylesheet.css</code>

If i use <code>git add</code> then hit tab it will detect that I am most likely looking to add the only modified file and autocomplete the string for me. Ending in <code>git add wp-content/themes/css/some-stylesheet.css</code>

If i use <code>ga</code> and hit tab it does nothing unless i tab twice and it list the directories that i can go into.

**Comment by salcode** [comment]
Since there has been no movement on this problem and I've been unable to recreate it, I'm closing this issue.  Feel free to re-open with more details if the problem still exists.
