### ISSUE TITLE
Possible New Aliases to Add?

### ISSUE THREAD

**Issue by salcode** [ironcodestudio/ironcode-git-enhancements#8]
This article has some interesting aliases it might be nice to add.
http://haacked.com/archive/2014/07/28/github-flow-aliases/

**Comment by salcode** [comment]
Also worth reviewing https://gist.github.com/christianacca/4d31bb0f1126a352a3c2

**Comment by codenameEli** [comment]
Here is a list of all the aliases for the oh-my-zsh plugin
https://github.com/robbyrussell/oh-my-zsh/wiki/Plugin:git

**Comment by salcode** [comment]
Nice list @codenameEli, I'll check it out.

Thanks.

**Comment by salcode** [comment]
Reviewed http://haacked.com/archive/2014/07/28/github-flow-aliases/, none I want to add at this time.

Reviewed https://gist.github.com/christianacca/4d31bb0f1126a352a3c2, none I want to add at this time.

Reviewed https://github.com/robbyrussell/oh-my-zsh/wiki/Plugin:git, none I want to add at this time.
